services:
  - type: web
    name: video-platform-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: "https://communication-platform-1.onrender.com"
        scope: run_time

  - type: static_site
    name: video-platform-frontend
    staticPublishPath: build
    buildCommand: npm install && npm run build
    envVars:
      - key: REACT_APP_SERVER_URL
        value: "https://communication-platform.onrender.com"
        scope: build_time
